apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-spring-app
  name: demo-spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-spring-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-spring-app
    spec:
      containers:
        - image: replace_me_to_pull_the_right_docker_image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          name: demo-spring-app
